World_books/pythonProject/WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from catalog import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('edit1/<int:id>', views.edit1, name='edit1'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(),
            name='book-detail'),
    re_path(r'^authors/(?P<pk>\d+)?$', views.AuthorListView.as_view(),
            name='authors'),
    # Tizimga kirish uchun URL-manzillarni qo`shish
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('catalog/', include('catalog.urls')),
]

World_books/pythonProject/WebBooks/catalog/urls.py
from django.template.defaulttags import url
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from setuptools.extern import names

from .import views
# from .WebBooks.urls import urlpatterns

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors_add/', views.authors_add, name='authors_add'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns += [
    re_path(r'^book/create/$', views.BookCreate.as_view(),
        name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(),
        name='book_update'),
    re_path(r'book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(),
        name='book_delete'),
]

World_books/pythonProject/WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text=" Kitob janrini kiriting", verbose_name="Kitob janri")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20, help_text="Kitob tilini kiriting", verbose_name="Kitob tili")

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Muallif ismini kiriting",
                                  verbose_name="Muallif ismi")
    last_name = models.CharField(max_length=200,
                                 help_text="Muallif familiyasini kiriting",
                                 verbose_name="Muallif familiyasi",
                                 default="Unknown")
    date_of_birth = models.DateField(help_text="Tug`ilish sanasini kiriting", verbose_name="Tug`ilgan sana",
                                     null=True, blank=True)
    date_of_death = models.DateField(help_text="O`lim sanasini kiriting", verbose_name="O`lim sanasi",
                                     null=True, blank=True)

    def __str__(self):
        return self.last_name

class Book(models.Model):
    title = models.CharField(max_length=200, help_text="Kitob nomini kiriting", verbose_name="Kitob nomi")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, help_text="Kitob uchun janrni tanlang",
                              verbose_name="Kitob janri", null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, help_text='Kitob uchun tilni tanlang',
                                 verbose_name="Kitob tili", null=True)
    author = models.ManyToManyField('Author',
                                    help_text='Kitob muallifini tanlang',
                                    verbose_name='Kitob muallifi')
    summary = models.TextField(max_length=1000, help_text='Kitobning qisqacha tavsifini kiriting',
                               verbose_name='Kitob annotatsiyasi')
    isbn = models.CharField(max_length=13,
                            help_text='13 ta belgidan iborat bo`lishi kerak',
                            verbose_name='kitob ISBNi')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Kitobning muayyan nusxasiga o`tish uchun URL-manzilni qaytaradi.
        return reverse('catalog:book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = 'Mualliflar'

class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Kitob nusxasining statusini kiriting",
                            verbose_name="Kitob nusxasi statusi")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE,
                             null=True,
                             verbose_name="Kitob nomi")
    inv_nom = models.CharField(max_length=20, null=True,
                               help_text='Nusxaning inventar raqamini kiriting',
                               verbose_name='Inventar raqami')
    imprint = models.CharField(max_length=200,
                               help_text="Nashriyot va nashr yilini kiriting",
                               verbose_name='Nashriyot')
    status = models.ForeignKey('Status', on_delete=models.CASCADE,
                               null=True,
                               help_text='Nusxa holatini o`zgartirish',
                               verbose_name='Kitob nusxasi statusi')
    due_back = models.DateField(null=True, blank=True,
                                help_text='Status muddati yakunini kiriting',
                                verbose_name='Status yakuni sanasi')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name="Buyurtmachi",
                                 help_text="Kitob buyurtmachisini tanlang")

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

World_books/pythonProject/WebBooks/catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book

class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']

class AuthorsForm(forms.Form):
    first_name = forms.CharField(label="Muallif ismi")
    last_name = forms.CharField(label="Muallif familiyasi")
    date_of_birth = forms.DateField(label="Tug`ilgan sana",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type':'date'}))
    date_of_death = forms.DateField(label="O`lim sanasi",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type':'date'}))

World_books/pythonProject/WebBooks/catalog/views.py
from django.http import *
from django.shortcuts import render
from .forms import AuthorsForm
from .models import Book, Author, BookInstance, Genre
from django.views.generic import ListView
from django.views import generic
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import  reverse_lazy
from .models import Book

class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

# mualliflar haqidagi mal`umotlarning MBda saqlanishi
def create(request):
    if request.method == "POST":
        author = Author()
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add")

# mualliflarni MBdan o`chirish
def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/authors_add/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("<h2>Muallif topilmadi</h2>")

# MBdagi mal`umotlarni o`zgartirish
def edit1(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        author.first_name =  request.POST.get("first_name")
        author.last_name =  request.POST.get("last_name")
        author.date_of_birth =  request.POST.get("date_of_birth")
        author.date_of_death =  request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add/")
    else:
        return render(request, "edit1.html", {"author":author})

# ma`lumotlarni MBdan olish va authors_add.html shablonini yuklash
def authors_add(request):
    author = Author.objects.all()
    authorsform = AuthorsForm()
    return render(request, "catalog/authors_add.html",
                  {"form":authorsform, "author":author})

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    '''
    Joriy foydalanuvchining qo`lida bo`lgan kitoblar
    ko`rinishining universal klassi
    '''
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrower_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
                borrower=self.request.user,
                status__exact='2').order_by('due_back')




class BookListView(generic.ListView):
    model = Book
    template_name = 'books/book_list.html'

def index(request):
    # Ba`zi asosiy ob`yektlar "miqdori" generatsiyasi
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Mavjud kitoblar (status = "omborda")
    num_instances_available = (
        BookInstance.objects.filter(status__exact=2).count())
    num_authors = Author.objects.count() # 'all()' metodi sukut bo`yicha qo`llanilgan

    # session o`zgaruvchisida sanalgan, bu viewga kirishlar soni
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # index.html HTML-shablonining context o`zgaruvchisi tarkibidagi
    # ma`lumotlar bilan tayyorlanishi
    return render(request, 'index.html',
                  context={'num_books':num_books,
                           'num_instances':num_instances,
                           'num_instances_available':num_instances_available,
                           'num_authors':num_authors,
                           'num_visits':num_visits}
                  )

class BookDetailView(DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'

class BookListView(generic.ListView):
    model = Book
    paginate_by = 3
    ordering = ['title']

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4

World_books/pythonProject/WebBooks/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}}

{% block content %}
    <h1>MB dagi mualliflar ro`yxati</h1>
    {% if author_list %}
        {% for author in author_list.all %}
        <p>{{ author.first_name }} {{ author.last_name }},
            <strong>Tug`ilgan-</strong>{{ author.date_of_birth }},
            <strong>Vafot etdi-</strong>{{ author.date_of_death }}</p>
        {% endfor %}
    {% else %}
        <p>Ma`lumotlar bazasida mualliflar mavjud emas</p>
    {% endif %}
{% endblock %}

World_books/pythonProject/WebBooks/catalog/templates/catalog/authors_add.html
{% extends "base_generic.html" %}
{% block content %}
<h3>MBdagi mualliflar ro`yxati</h3>
  <table>
    <thead>
      <th>Id</th><th>----Ism----</th><th>Familiya</th><th></th>
    </thead>
    {% if author %}
      {% for author in author.all %}
        <tr>
          <td>{{author.id}}</td>
          <td>{{author.first_name}}</td>
          <td>{{author.last_name}}</td>
          <td><a href="/edit1/{{author.id}}">O`zgartirish</a>,
              <a href="/delete/{{author.id}}">O`chirish</a></td>
        </tr>
      {% endfor %}
    {% else %}
      <p>Ma`lumotlar bazasida mualliflar mavjud emas</p>
    {% endif %}
  </table>

<h3>MBga kitob muallifini qo`shish</h3>
<form method="POST" action="/create/">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" value="Saqlash">
</form>
{% endblock %}

World_books/pythonProject/WebBooks/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Kitobni o`chirish</h1>
<p>Chindan {{ book }} kitobini o`chirmoqchimisiz?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Ha, o`chiramiz"/>
</form>

{% endblock %}

World_books/pythonProject/WebBooks/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Kitob nomi: {{ book.title }}</h1>
    <p><strong>Janr: </strong>{{ book.genre }}</p>
    <p><strong>Annotatsiya: </strong>{{ book.summary }}</p>
    <p><strong>ISBN: </strong>{{ book.isbn }}</p>
    <p><strong>Til: </strong>{{ book.language }}</p>
        {% for author in book.author.all %}
            <p><strong>Muallif: </strong>
                <a href="">{{ author.first_name }}
                           {{ author.last_name }}</a></p>
        {% endfor %}
<div style="margin-left:20px;margin-top:20px">
    <h4>Kitobning MBdagi nusxalari miqdori</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr><p class="{% if copy.status == 1 %} text-success
                {% elif copy.status == 2 %} text-danger
                {% else %} text-warning
                {% endif %}"> {{ copy.get_status_display }} </p>
    <p><strong>Nashriyot: </strong>{{ copy.imprint }}</p>
    <p class="text-muted"><strong>Inventar raqami: </strong>{{ copy.id }}</p>
    <p><strong>Kitob nusxasining MBdagi statusi: </strong>{{ copy.status }}</p>
    {% endfor %}
</div>
{% endblock %}
<p><strong>Muallif:</strong><a href="">{{ author.first_name }}
{{ author.last_name }}</a></p>

World_books/pythonProject/WebBooks/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ forms.as_table }}
  </table>
</form>
{% endblock %}

World_books/pythonProject/WebBooks/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>MBdagi kitoblar ro`yxati</h1>
  {% if book_list %}
  <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">
                  {{ book.title }} </a>
                  ({{ book.genre }})
          <a href="/book/update/{{book.id}}">O`zgartirish</a>
          <a href="/book/delete/{{book.id}}">O`chirish</a>
      </li>
      {% endfor %}
  </ul>
      {% else %}
        <p>Ma`lumotlar bazasida kitob yo`q</p>
      {% endif %}
{% endblock %}

World_books/pythonProject/WebBooks/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Olingan kitoblar</h1>

    {% if bookinctance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %} text-danger {% endif %}">
            <a href="{% url 'book-detail'bookinst.book.pk %}"></a>
                        ({{ bookinst.due_back }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>BUYURTMADA statusli kitoblar mavjud emas</p>
    {% endif %}
{% endblock %}