World_books/pythonProject/WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from catalog import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('edit1/<int:id>', views.edit1, name='edit1'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(),
            name='book-detail'),
    re_path(r'^authors/(?P<pk>\d+)?$', views.AuthorListView.as_view(),
            name='authors'),
    # Tizimga kirish uchun URL-manzillarni qo`shish
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('catalog/', include('catalog.urls')),
]

World_books/pythonProject/WebBooks/catalog/urls.py
from django.template.defaulttags import url
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from setuptools.extern import names

from .import views
# from .WebBooks.urls import urlpatterns

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors_add/', views.authors_add, name='authors_add'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns += [
    re_path(r'^book/create/$', views.BookCreate.as_view(),
        name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(),
        name='book_update'),
    re_path(r'book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(),
        name='book_delete'),
]

World_books/pythonProject/WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text=" Kitob janrini kiriting", verbose_name="Kitob janri")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20, help_text="Kitob tilini kiriting", verbose_name="Kitob tili")

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Muallif ismini kiriting",
                                  verbose_name="Muallif ismi")
    last_name = models.CharField(max_length=200,
                                 help_text="Muallif familiyasini kiriting",
                                 verbose_name="Muallif familiyasi",
                                 default="Unknown")
    date_of_birth = models.DateField(help_text="Tug`ilish sanasini kiriting", verbose_name="Tug`ilgan sana",
                                     null=True, blank=True)
    date_of_death = models.DateField(help_text="O`lim sanasini kiriting", verbose_name="O`lim sanasi",
                                     null=True, blank=True)

    def __str__(self):
        return self.last_name

class Book(models.Model):
    title = models.CharField(max_length=200, help_text="Kitob nomini kiriting", verbose_name="Kitob nomi")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, help_text="Kitob uchun janrni tanlang",
                              verbose_name="Kitob janri", null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, help_text='Kitob uchun tilni tanlang',
                                 verbose_name="Kitob tili", null=True)
    author = models.ManyToManyField('Author',
                                    help_text='Kitob muallifini tanlang',
                                    verbose_name='Kitob muallifi')
    summary = models.TextField(max_length=1000, help_text='Kitobning qisqacha tavsifini kiriting',
                               verbose_name='Kitob annotatsiyasi')
    isbn = models.CharField(max_length=13,
                            help_text='13 ta belgidan iborat bo`lishi kerak',
                            verbose_name='kitob ISBNi')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Kitobning muayyan nusxasiga o`tish uchun URL-manzilni qaytaradi.
        return reverse('catalog:book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = 'Mualliflar'

class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Kitob nusxasining statusini kiriting",
                            verbose_name="Kitob nusxasi statusi")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE,
                             null=True,
                             verbose_name="Kitob nomi")
    inv_nom = models.CharField(max_length=20, null=True,
                               help_text='Nusxaning inventar raqamini kiriting',
                               verbose_name='Inventar raqami')
    imprint = models.CharField(max_length=200,
                               help_text="Nashriyot va nashr yilini kiriting",
                               verbose_name='Nashriyot')
    status = models.ForeignKey('Status', on_delete=models.CASCADE,
                               null=True,
                               help_text='Nusxa holatini o`zgartirish',
                               verbose_name='Kitob nusxasi statusi')
    due_back = models.DateField(null=True, blank=True,
                                help_text='Status muddati yakunini kiriting',
                                verbose_name='Status yakuni sanasi')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name="Buyurtmachi",
                                 help_text="Kitob buyurtmachisini tanlang")

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

World_books/pythonProject/WebBooks/catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book

class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']

class AuthorsForm(forms.Form):
    first_name = forms.CharField(label="Muallif ismi")
    last_name = forms.CharField(label="Muallif familiyasi")
    date_of_birth = forms.DateField(label="Tug`ilgan sana",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type':'date'}))
    date_of_death = forms.DateField(label="O`lim sanasi",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type':'date'}))

World_books/pythonProject/WebBooks/catalog/views.py
from django.http import *
from django.shortcuts import render
from .forms import AuthorsForm
from .models import Book, Author, BookInstance, Genre
from django.views.generic import ListView
from django.views import generic
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import  reverse_lazy
from .models import Book

class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

# mualliflar haqidagi mal`umotlarning MBda saqlanishi
def create(request):
    if request.method == "POST":
        author = Author()
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add")

# mualliflarni MBdan o`chirish
def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/authors_add/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("<h2>Muallif topilmadi</h2>")

# MBdagi mal`umotlarni o`zgartirish
def edit1(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        author.first_name =  request.POST.get("first_name")
        author.last_name =  request.POST.get("last_name")
        author.date_of_birth =  request.POST.get("date_of_birth")
        author.date_of_death =  request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add/")
    else:
        return render(request, "edit1.html", {"author":author})

# ma`lumotlarni MBdan olish va authors_add.html shablonini yuklash
def authors_add(request):
    author = Author.objects.all()
    authorsform = AuthorsForm()
    return render(request, "catalog/authors_add.html",
                  {"form":authorsform, "author":author})

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    '''
    Joriy foydalanuvchining qo`lida bo`lgan kitoblar
    ko`rinishining universal klassi
    '''
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrower_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
                borrower=self.request.user,
                status__exact='2').order_by('due_back')




class BookListView(generic.ListView):
    model = Book
    template_name = 'books/book_list.html'

def index(request):
    # Ba`zi asosiy ob`yektlar "miqdori" generatsiyasi
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Mavjud kitoblar (status = "omborda")
    num_instances_available = (
        BookInstance.objects.filter(status__exact=2).count())
    num_authors = Author.objects.count() # 'all()' metodi sukut bo`yicha qo`llanilgan

    # session o`zgaruvchisida sanalgan, bu viewga kirishlar soni
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # index.html HTML-shablonining context o`zgaruvchisi tarkibidagi
    # ma`lumotlar bilan tayyorlanishi
    return render(request, 'index.html',
                  context={'num_books':num_books,
                           'num_instances':num_instances,
                           'num_instances_available':num_instances_available,
                           'num_authors':num_authors,
                           'num_visits':num_visits}
                  )

class BookDetailView(DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'

class BookListView(generic.ListView):
    model = Book
    paginate_by = 3
    ordering = ['title']

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4

World_books/pythonProject/WebBooks/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Kitoblar dunyosi</title> {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Statik CSS faylni qo`shish -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block head %}
    <img src="{% static 'images/logotip.jpg' %}"
    style="width:100px; height:100px;" align="absmiddle">
    <span style="font-size: 2rem; color: blue;">"Kitoblar dunyosi" sayti</span>
  {% endblock %}
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'catalog:index' %}">Asosiy sahifa</a></li>
          <li><a href="{% url 'books' %}">Barcha kitoblar</a></li>
          <li><a href="{% url 'authors' %}">Barcha mualliflar</a></li>
          <li><a href="{% url 'catalog:authors_add' %}">Mualliflarni tahrirlash</a></li>
          <li><a href="{% url 'catalog:book_create' %}">Kitob qo`shish</a></li>
        </ul>

          {% if user.is_authenticated %}
            <li>Foydalanuvchi: {{ user.get_username }}</li>
            <li>
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" style="border:none; background:none; padding:0; color:blue; cursor:pointer;">
                  Chiqish
                </button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Kirish</a></li>
          {% endif %}
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %} {% endblock %}
        {% block pagination %}
          {% if is_paginated %}
            <div class="page-links">
              <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="?page={{page_obj.previous_page_number}}"> Oldingisi </a>
                {% endif %}
                <span class="page-current">
                  Jami {{ page_obj.paginator.num_pages }} tadan
                  {{ page_obj.number }} -sahifa
                </span>
                  {% if page_obj.has_next %}
                    <a href="?page={{page_obj.next_page_number }}"> Keyingisi </a>
                    <!--<a href="{{ request.path }}?page={{
                            page_obj.next_page_number }}
                            "> Keyingisi </a> -->
                  {% endif %}
                </span>
            </div>
          {% endif %}
        {% endblock %}

        {% block footer %}
          {% block copyright %}
            <p>Copyright "Inson va kitob" MChJ, 2024. Barcha huquqlar himoyalangan</p>
          {% endblock %}
        {% endblock %}

      </div>
    </div>
  </div>
</body>
</html>

World_books/pythonProject/WebBooks/catalog/templates/edit1.html
{% extends "base_generic.html" %}
{% block content %}

  <h3>MBdagi mualliflar ro`yxati</h3>
  <h4>{{author.first_name}} {{author.last_name}}</h4>
    <form method="POST">
      {% csrf_token %}
      <p>
        <label>Ismni o`zgartiring</label><br>
        <input type="text" name="first_name" value="{{author.first_name}}">
      </p>
      <p>
        <label>Familiyani o`zgartiring</label><br>
        <input type="text" name="last_name" value="{{author.last_name}}">
      </p>
      <p>
        <label>Tug`ilgan sanani o`zgartiring</label><br>
        <input type="date" name="date_of_birth" value="{{author.date_of_birth}}">
      </p>
      <p>
        <label>O`lim sanasini o`zgartiring</label><br>
        <input type="date" name="date_of_death" value="{{author.date_of_death}}">
      </p>
      <input type="submit" value="Saqlash">
    </form>
{% endblock %}

World_books/pythonProject/WebBooks/catalog/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Asosiy sahifa</h1>
    <p><em>Kitoblar dunyosi</em>ga xush kelibsiz, Bu Djangoda tayyorlangan,
        juda ham oddiy sayt. PyCharmdan foydalangan holda, Pythonda
        tayyorlangan</p>

<h2>Dinamik kontent</h2>
    <p>Kitoblar dunyosi saytining ma`lumotlar bazasida
        quyidagicha miqdordagi yozuvlar mavjud: </p>
    <ul>
        <li><strong>Kitoblar soni: </strong>{{ num_books }}</li>
        <li><strong>Kitoblar nusxalari soni:</strong> {{ num_instances }} </li>
        <li><strong>Buyurtmadagi kitoblar nusxalari soni:
            </strong> {{ num_instances_available }}</li>
        <li><strong>Kitoblar mualliflari soni:
        </strong> {{ num_authors }}</li>
    </ul>
    <p>Ushbu sahifaga kirishlar soni - {{ num_visits }}</p>
{% endblock %}